name: Package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  verify-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Update Version
      uses: Amadevus/pwsh-script@v2.0.1
      id: update-version
      with:
        script: |
          $file = Get-ChildItem -Path "$($github.workspace)" -Filter "*Fluetax.csproj" -Recurse
          if($null -eq $file){
              throw "Failed to find csproj"
          }
          $csproj = [xml](Get-Content $file.FullName)

          $d = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::Now,"Pacific Standard Time") | Get-Date -Hour 0 -Minute 0 -Second 0
          $diff = ((Get-Date) - $d)
          $seconds = [Math]::Round($diff.TotalSeconds / 2)
          $ver = "$($d.ToString('yyyy.MM.dd')).$seconds"

          $csproj.SelectSingleNode("//Version").InnerText = $ver
          Write-ActionInfo "Version: $ver"
          $csproj.Save($file.FullName)
          return 0
      continue-on-error: false
    - name: Build Release
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/lzinga/index.json --skip-duplicate --no-symbols true
